
server.port=${PORT:10000}

spring.main.allow-bean-definition-overriding=true


spring.datasource.url=jdbc:postgresql://ep-delicate-mud-amz0venw-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MwTriELK70kG
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${MY_MAIL_USER}
spring.mail.password=${MY_MAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000